version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php-container
    command: sh -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache && chmod -R 775 /var/www/storage /var/www/bootstrap/cache && php-fpm"
    volumes:
      - .:/var/www
      - storage-data:/var/www/storage
    networks:
      - app-network

  nginx:
    image: nginx:stable
    container_name: nginx-container
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app-network
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  storage-data:
